[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
hyper = "1.6.0"
tower = "0.5.2"
